import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Disabilita scroll restoration del browser PRIMA del paint per evitare
            che Safari iOS / Chrome ripristinino una posizione precedente quando
            si arriva su una pagina via hard-nav (es. middleware rewrite di
            /en/residences → /en/residenze). Lo scroll viene gestito da
            <ScrollToTop /> e dai save/restore manuali su popstate. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{history.scrollRestoration='manual'}catch(e){}`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
